### ISSUE TITLE
What type of license does this package has?

### ISSUE THREAD

**Issue by patricksavalle** [dzieciou/curl-logger#19]
Is it allowed we use this library in our software?

**Comment by dzieciou** [comment]
Thanks for asking.

The library has BSD License, Revised,  https://opensource.org/licenses/BSD-3-Clause. Feel free to use it.

Out of curiosity, what software it will be used in?

**Comment by patricksavalle** [comment]
Is for the booking software of NS International, Dutch rail transport. Bookings of high-speed trains etc.
