### ISSUE TITLE
Want the curl logger output to be stored in some variable to display on other places or add curl in reports

### ISSUE THREAD

**Issue by kalpeshchilka** [dzieciou/curl-logger#42]
Hi,

Is it possible to store the curl logger output to be stored in some variable to display on other places or add curl output in reports for better display?

**Comment by maddysk3** [comment]
@dzieciou same here as of now the curl is getting printed in the logs from below method:
`  public void process(HttpRequest request, HttpContext context) throws HttpException, IOException {
    try {
      String curl = http2Curl.generateCurl(request);
      StringBuffer message = new StringBuffer(curl);
      if (options.canLogStacktrace()) {
        message.append(String.format("%n\tgenerated%n"));
        System.out.println(message);
        printStacktrace(message);
      }
      log.debug(message.toString());
    } catch (Exception e) {
      log.warn("Failed to generate CURL command for HTTP request", e);
    }
  `
I want to store the message which is generated from String buffer so that I can embed it in the reports to make it easy for developers to debug API calls.

**Comment by dzieciou** [comment]
Interesting idea although this feature is not currently supported.

 One way would be to create a new class `CurlStoringInterceptor` that inherits from `CurlLoggingInterceptor` and overrides `process()` method:

```java
public CurlLoggingInterceptor(Options options, Report report) {
    this.options = options;
    this.report = report
    http2Curl = new Http2Curl(options);
  }

public void process(HttpRequest request, HttpContext context) throws HttpException, IOException {
    try {
      String curl = http2Curl.generateCurl(request);
      self.report.add(curl)
```

You may also consider adding also information about test name in the constructor to associate curls with specific tests in the report.

This would require updating also `CurlLoggingRestAssuredConfigFactory.java`

**Comment by kalpeshchilka** [comment]
@dzieciou We are having a hard time copying the curl output directly into the reports as per your previously mentioned code. Can you just help us to copy the cURL logger output to store in some variable?  Later we will play around with that variable. 
Please lets us know if its possible or share sample running code would of great help!

**Comment by dzieciou** [comment]
@kalpeshchilka Feel free to provide pull request that the feature you need. Unfortunately, I have limited time to help maintain and add new features to the library but I can review your pull request.

**Comment by maddysk3** [comment]
@kalpeshchilka you can use the below mentioned code in your TestNG Test Class

`public class <YOURTESTCLASSNAME> {
	public static String finalcurl;
	private static TestLogger log;

	  private static RestAssuredConfig getRestAssuredConfig(
	      CurlLoggingInterceptor curlLoggingInterceptor) {
	    return config()
	        .httpClient(httpClientConfig()
	            .reuseHttpClientInstance()
	            .httpClientFactory(new MyHttpClientFactory(curlLoggingInterceptor)));
	  }
	  
	  public static class MyHttpClientFactory implements HttpClientConfig.HttpClientFactory {
		    private final CurlLoggingInterceptor curlLoggingInterceptor;
		    public MyHttpClientFactory(CurlLoggingInterceptor curlLoggingInterceptor) {
		      this.curlLoggingInterceptor = curlLoggingInterceptor;
		    }

		    @Override
		    public HttpClient createHttpClient() {
		      @SuppressWarnings("deprecation") AbstractHttpClient client = new DefaultHttpClient();
		      client.addRequestInterceptor(curlLoggingInterceptor);
		      return client;
		    }
		  }
	
	@Test
	public static void getMethod(String env, String envParameter) throws IOException {
	log = TestLoggerFactory.getTestLogger("curl");
	    log.clearAll();
	    Options OPTIONS = Options.builder().dontLogStacktrace().printMultiliner().build();
	    RestAssuredConfig restAssuredConfig = getRestAssuredConfig(new CurlLoggingInterceptor(OPTIONS));
		Response responseBody = given().config(restAssuredConfig)
				.when()
				.get(<YOURAPIURL>).then()
				.extract().response();
		LoggingEvent firstEvent = log.getLoggingEvents().get(0);
	  String  finalcurl=firstEvent.getMessage();
	}`

**finalcurl** is the variable where your curl is saved

Hope this helps!

**Comment by dzieciou** [comment]
In 2.0.0 version I plan to release support for custom handlers:

> By default generated curls are logged. However, there's a way to process curl by one or more custom handlers by providing a list of custom handlers, implementing CurlHandler interface. For instance, to store generated curls in a variable one could write:

>```java
final List<String> curls = new ArrayList<>();
CurlHandler handler = new CurlHandler() {
  @Override
  public void handle(String curl, Options options) {
    curls.add(curl);
  }
};
List<CurlHandler> handlers = Arrays.asList(handler);
CurlRestAssuredConfigFactory.createConfig(handlers)
```

**Comment by kalpeshchilka** [comment]
Thank you @maddysk3 for the workaround, currently using that. Also @dzieciou, thank you for the version 2.0.0 with more options, will surely try this.
