### ISSUE TITLE
Rename parameter s to name

### ISSUE THREAD

**Issue by dzieciou** [dzieciou/curl-logger#46]
https://github.com/dzieciou/curl-logger/blob/81bf37345df9e426ddee1428bbfa80c12d606101/src/main/java/com/github/dzieciou/testing/curl/Http2Curl.java#L267

**Comment by Being-Maverick** [comment]
Hey, @dzieciou I would like to work on this. Please assign it to me.

**Comment by dzieciou** [comment]
@Being-Maverick Thanks for help. Feel free to provide a pull request

**Comment by dzieciou** [comment]
Fixed. Thanks.
