### ISSUE TITLE
On Maven Central Repository, the artifact version 1.0.5 does not have latest code.

### ISSUE THREAD

**Issue by msuhaib7** [dzieciou/curl-logger#49]
Have checked the latest master and found `public Builder useLogLevel(Level level)` method which I was looking for, but on the maven central, 1.0.5 version does not have the code.

**Comment by dzieciou** [comment]
That's because that change is part of 2.0.0 version that has not been released yet.

**Comment by dzieciou** [comment]
The change has been released in 2.0.0. 

Available now for download: https://repo1.maven.org/maven2/com/github/dzieciou/testing/curl-logger/2.0.0/
