### ISSUE TITLE
Can you modify the CurlHandler interface from default to public? 

### ISSUE THREAD

**Issue by Tigran94** [dzieciou/curl-logger#56]

**Comment by dzieciou** [comment]
What would be the motivation? / Use case?

**Comment by Tigran94** [comment]
I wanna use Custom curl handling which you described here https://github.com/dzieciou/curl-logger#custom-curl-handling

**Comment by dzieciou** [comment]
🤦 Let's pretend I haven't done this bug

It will be fixed on 2.0.1 version.
