### ISSUE TITLE
Allow for always printing requestMethod

### ISSUE THREAD

**Issue by lcardito** [dzieciou/curl-logger#60]
Hey team! 

First of all awesome work here! I'm planning to use this as a way of publishing internal documentation in the form of `curl` commands.

I was wondering if we could add a configuration option to always print the `requestMethod` in the curl command rather than skipping it when not necessary?

Happy to contribute with a PR if this sounds reasonable 😄

**Comment by dzieciou** [comment]
Sorry for late reply. I tend to maintain these project less frequently recently.

I like your idea! Feel free to submit PR :-)

**Comment by lcardito** [comment]
Thanks @dzieciou - lets see if I can find some time to get that in! :)

**Comment by dzieciou** [comment]
Merged I've refactored the method to `alwaysPrintMethod`.

**Comment by dzieciou** [comment]
Can you say more about your use case? I understand that you have use cases written with REST-assured and you want to document them with curl commands, so that other people can read curl commands instead of docs?

**Comment by lcardito** [comment]
> Can you say more about your use case? I understand that you have use cases written with REST-assured and you want to document them with curl commands, so that other people can read curl commands instead of docs?

Yes exactly. Our business and products are APIs. Our docs are always followed by examples and this is a great way to easily have them at hand :)
