### ISSUE TITLE
Storing logs generated by curl 

### ISSUE THREAD

**Issue by DikshaBaluja** [dzieciou/curl-logger#67]
Hi,
is it possible to store logs generated by curl after build creation in String format ? 

RequestSpecification spec = getRequestSpecification(RestAssured.given());
Response res = spec.config(config).when().post(this.url).then().extract().response();

Logs are generated post execution of above code. Is it possible to store these logs?
Thanks

**Comment by dzieciou** [comment]
Hi,

It depends what you mean by storing logs.

If you mean storing logs in a file, you can configure your logging library to log directly to a file. For instance, for logback logging library you can find example of configuring `FileAppender` [here](https://github.com/qos-ch/logback/blob/master/logback-examples/src/main/resources/chapters/appenders/conf/logback-fileAppender.xml).

If you mean storing logs in a variable, example in section on (`Custom CURL handling`)[https://github.com/dzieciou/curl-logger#custom-curl-handling].

**Comment by DikshaBaluja** [comment]
Yes, it was in readme section , custom curl handling , I got it
Thanks
