### ISSUE TITLE
[Question] Exclude Cookies

### ISSUE THREAD

**Issue by iamrulloh** [dzieciou/curl-logger#74]
Hi, is there any way to exclude the cookies in the generated curl log? I've tried to use `.removeHeader("Cookie")` but the cookies still appear in the log, because its use `-b` instead of `-H`.

**Comment by dzieciou** [comment]
Hi! Thanks for raising this issue.

I've prepared pull request #75 that fixes the issue. Should be merged in the next release.

**Comment by iamrulloh** [comment]
Great! Thank you
