### ISSUE TITLE
Latest version is not on on the maven repo (0.6)

### ISSUE THREAD

**Issue by orshachar** [dzieciou/curl-logger#8]
Hey, the latest version does not exist here as a tag and can't be found on : https://mvnrepository.com/artifact/com.github.dzieciou.testing/curl-logger

Can it be added there? 

Thanks!

**Comment by dzieciou** [comment]
I'm working on using online Travis CI to automatically deploy release versions to Maven Central. I should get this done this week. I will notify you in this thread.

**Comment by orshachar** [comment]
Thanks a lot!

**Comment by bradywood** [comment]
any update on version 0.6?

**Comment by dzieciou** [comment]
@orshachar , @bradywood  v0.6 is now in Maven Central http://repo1.maven.org/maven2/com/github/dzieciou/testing/curl-logger/0.6/. It might up to our to be indexed by Maven Search but you should be able to use it even before.

It took me longer than expected, but now all releases from release branch should be deployed to Maven Central automatically by Travis CI. So no manual releases anymore.
